import type { Metadata } from "next";
import "./globals.css";
import { manrope, myFont, roboto } from "@/components/font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${roboto.variable} ${myFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
